export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const GET_ERRORS = 'GET_ERRORS';

export const WORKOUT_DAYS_LIST_FETCHED_SUCCESS = 'WORKOUT_DAYS_LIST_FETCHED_SUCCESS';
export const WORKOUT_DAYS_LIST_FETCHED_ERROR = 'WORKOUT_DAYS_LIST_FETCHED_ERROR';

export const WORKOUT_DAY_FETCHED_SUCCESS = 'WORKOUT_DAY_FETCHED_SUCCESS';

//exercises/ workouts
export const EXCERCISES_WORKOUT_FETCHED_SUCCESS = 'EXCERCISES_WORKOUT_FETCHED_SUCCESS';
export const EXCERCISE_FETCHED_SUCCESS = 'EXCERCISE_FETCHED_SUCCESS';
export const EXCERCISE_FETCHED_ERROR = 'EXCERCISE_FETCHED_ERROR';
export const EXCERCISES_WORKOUT_FETCHED_ERROR = 'EXCERCISES_WORKOUT_FETCHED_ERROR';


export const WORKOUT_SESSION_FETCHED_SUCCESS = 'WORKOUT_SESSION_FETCHED_SUCCESS';
export const WORKOUT_SESSION_ADDED_SUCCESS = 'WORKOUT_SESSION_ADDED_SUCCESS';
export const WORKOUT_LAST_SESSION_FETCHED_SUCCESS = 'WORKOUT_LAST_SESSION_FETCHED_SUCCESS';
